


##################################
# https://itsfoss.com/hyprland/

# Install Hyprland

# on Arch
sudo pacman -S kitty hyprland


# Hyprland config
nano ~/.config/hypr/hyprland.config
# remove the like:
# autogenerated = 1



# Important key bindings:

# SUPER + SHIFT + <number> = switches to the workspace #<number>
# SUPER + RIGHT = switches to the tiling window to the right of the currently selected (left, up, down similarly)

##################################
# waybar
##################################

# https://itsfoss.com/configure-waybar/

sudo pacman -Syu waybar

nano ~/.config/hypr/hyprland.conf
# add exec-once=waybar


#Default config:  https://github.com/Alexays/Waybar/blob/master/resources/config.jsonc

mkdir -p ~/.config/waybar
# get the default waybar config
wget https://raw.githubusercontent.com/Alexays/Waybar/refs/heads/master/resources/config.jsonc -O ~/.config/waybar/config.jsonc
# do not use nano
codium ~/.config/waybar/config.jsonc

exec-once=waybar

##################################
# Wallpapers
##################################

# https://itsfoss.com/hyprpaper-hyprland/
sudo pacman -S hyprpaper

# Hyprpaper expects its configuration file at ~/.config/hypr/hyprpaper.conf. You need to create this file to configure the program.

nano ~/.config/hypr/hyprpaper.conf
# add the following to this file:
# preload=path/to/wallpaper/image
# wallpaper=<monitor-name>,path/to/wallpaper/image

# how to get monitor name?
hyprctl monitors

# preload=/nbhirud/nb/wallpaper/IMG-20241020-WA0014.jpg
# wallpaper=VGA-1,/nbhirud/nb/wallpaper/IMG-20241020-WA0014.jpg
# splash = false

exec-once = hyprpaper

##################################
# Customizing Hyprland
##################################

# https://itsfoss.com/configuring-hyprland/


##################################
# Set a notification daemon
##################################

sudo pacman -Syu dunst
notify-send "Hello World!"
exec-once = dunst


##################################
# Clipboard manager
##################################

sudo pacman -Syu copyq

exec-once = copyq --start-server

##################################
# screenshot utility
##################################
sudo pacman -Syu jq grim slurp wl-clipboard libnotify
yay -S hyprshot

nano ~/.config/hypr/hyprland.conf
# add the following to the KEYBINDINGS section

# Screenshot a window
# bind = , PRINT, exec, hyprshot -m region


##################################
# Hyprcursor
##################################
# https://wiki.hyprland.org/Hypr-Ecosystem/hyprcursor/

yay -S rose-pine-hyprcursor


nano ~/.config/hypr/hyprland.conf
# set the HYPRCURSOR_THEME environment variable
# env = HYPRCURSOR_THEME,rose-pine-hyprcursor

# set the cursor size: run on terminal:
hyprctl setcursor rose-pine-hyprcursor 26


##################################
# 
##################################




##################################
# 
##################################




##################################
# 
##################################




##################################
# 
##################################





##################################
# 
##################################




