site_name: System & Code Notes
site_url: https://sysupdate.nbhirud.com # Update with your CNAME if you have one
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: purple
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["."] # Allows referencing files from the root directory
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

# Map your existing folders directly to navigation tabs
nav:
  - Home: README.md
  - Linux: linux/
  - Python: python/
  - Android: android/
  - Git: git/
  - WSL: wsl/
  - Windows: windows/
  - macOS: macos/
  - Data Recovery: data_recovery/
  - Misc: misc/

# Tell MkDocs which files to exclude from the final build (keep code private or uncompiled)
exclude_docs: |
  # *.py
  # *.sh
  # *.rs
  .idea/
  .git/
  _config.ymls