name: ci

on:
  push:
    branches:
      - main # or master, depending on your default branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-24.04 # ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Configure Git Credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v5 # actions/setup-python@v7
        with:
          python-version: "3.x"
          
      - name: Install dependencies
        run: |
          pip install mkdocs-material
          
      - name: Build and deploy
        run: |
          mkdocs gh-deploy --force
